"""add cin fields for president, vice-president, membres and suppleants

Revision ID: 0887a263802c
Revises: 5815cb34167e
Create Date: 2026-09-19 18:37:04.327669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0887a263802c'
down_revision: Union[str, None] = '5815cb34167e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bureaux_centraux', sa.Column('president_cin', sa.String(length=50), nullable=True))
    op.add_column('bureaux_centraux', sa.Column('vice_president_cin', sa.String(length=50), nullable=True))
    op.add_column('bureaux_centraux', sa.Column('membre_central_1_cin', sa.String(length=50), nullable=True))
    op.add_column('bureaux_centraux', sa.Column('membre_central_2_cin', sa.String(length=50), nullable=True))
    op.add_column('bureaux_centraux', sa.Column('membre_central_3_cin', sa.String(length=50), nullable=True))
    op.add_column('bureaux_centraux', sa.Column('suppleant_central_1_cin', sa.String(length=50), nullable=True))
    op.add_column('bureaux_centraux', sa.Column('suppleant_central_2_cin', sa.String(length=50), nullable=True))
    op.add_column('bureaux_centraux', sa.Column('suppleant_central_3_cin', sa.String(length=50), nullable=True))
    op.add_column('bureaux_vote', sa.Column('president_cin', sa.String(length=50), nullable=True))
    op.add_column('bureaux_vote', sa.Column('vice_president_cin', sa.String(length=50), nullable=True))
    op.add_column('bureaux_vote', sa.Column('membre_1_cin', sa.String(length=50), nullable=True))
    op.add_column('bureaux_vote', sa.Column('membre_2_cin', sa.String(length=50), nullable=True))
    op.add_column('bureaux_vote', sa.Column('membre_3_cin', sa.String(length=50), nullable=True))
    op.add_column('bureaux_vote', sa.Column('suppleant_1_cin', sa.String(length=50), nullable=True))
    op.add_column('bureaux_vote', sa.Column('suppleant_2_cin', sa.String(length=50), nullable=True))
    op.add_column('bureaux_vote', sa.Column('suppleant_3_cin', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bureaux_vote', 'suppleant_3_cin')
    op.drop_column('bureaux_vote', 'suppleant_2_cin')
    op.drop_column('bureaux_vote', 'suppleant_1_cin')
    op.drop_column('bureaux_vote', 'membre_3_cin')
    op.drop_column('bureaux_vote', 'membre_2_cin')
    op.drop_column('bureaux_vote', 'membre_1_cin')
    op.drop_column('bureaux_vote', 'vice_president_cin')
    op.drop_column('bureaux_vote', 'president_cin')
    op.drop_column('bureaux_centraux', 'suppleant_central_3_cin')
    op.drop_column('bureaux_centraux', 'suppleant_central_2_cin')
    op.drop_column('bureaux_centraux', 'suppleant_central_1_cin')
    op.drop_column('bureaux_centraux', 'membre_central_3_cin')
    op.drop_column('bureaux_centraux', 'membre_central_2_cin')
    op.drop_column('bureaux_centraux', 'membre_central_1_cin')
    op.drop_column('bureaux_centraux', 'vice_president_cin')
    op.drop_column('bureaux_centraux', 'president_cin')
    # ### end Alembic commands ###
