"""create bureaux_vote and bureaux_centraux tables

Revision ID: 5815cb34167e
Revises: 
Create Date: 2026-09-18 20:01:40.223077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5815cb34167e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bureaux_centraux',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_bureau_central', sa.String(length=50), nullable=False),
    sa.Column('commune', sa.String(length=255), nullable=False),
    sa.Column('president_bureau_central', sa.String(length=255), nullable=False),
    sa.Column('adresse_bureau_central', sa.String(length=500), nullable=True),
    sa.Column('vice_president_bureau_central', sa.String(length=255), nullable=True),
    sa.Column('membre_central_1', sa.String(length=255), nullable=True),
    sa.Column('membre_central_2', sa.String(length=255), nullable=True),
    sa.Column('membre_central_3', sa.String(length=255), nullable=True),
    sa.Column('suppleant_central_1', sa.String(length=255), nullable=True),
    sa.Column('suppleant_central_2', sa.String(length=255), nullable=True),
    sa.Column('suppleant_central_3', sa.String(length=255), nullable=True),
    sa.Column('numero_decision', sa.String(length=50), nullable=True),
    sa.Column('date_signature', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commune', 'numero_bureau_central', name='uq_central_commune_numero')
    )
    op.create_index(op.f('ix_bureaux_centraux_commune'), 'bureaux_centraux', ['commune'], unique=False)
    op.create_index(op.f('ix_bureaux_centraux_numero_bureau_central'), 'bureaux_centraux', ['numero_bureau_central'], unique=False)
    op.create_table('bureaux_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_bureau', sa.String(length=50), nullable=False),
    sa.Column('commune', sa.String(length=255), nullable=False),
    sa.Column('adresse_bureau', sa.String(length=500), nullable=False),
    sa.Column('president', sa.String(length=255), nullable=False),
    sa.Column('vice_president', sa.String(length=255), nullable=False),
    sa.Column('numero_bureau_central', sa.String(length=50), nullable=False),
    sa.Column('president_bureau_central', sa.String(length=255), nullable=False),
    sa.Column('adresse_bureau_central', sa.String(length=500), nullable=True),
    sa.Column('membre_1', sa.String(length=255), nullable=False),
    sa.Column('membre_2', sa.String(length=255), nullable=False),
    sa.Column('membre_3', sa.String(length=255), nullable=False),
    sa.Column('suppleant_1', sa.String(length=255), nullable=False),
    sa.Column('suppleant_2', sa.String(length=255), nullable=False),
    sa.Column('suppleant_3', sa.String(length=255), nullable=False),
    sa.Column('numero_decision', sa.String(length=50), nullable=True),
    sa.Column('date_signature', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commune', 'numero_bureau', name='uq_bureau_commune_numero')
    )
    op.create_index(op.f('ix_bureaux_vote_commune'), 'bureaux_vote', ['commune'], unique=False)
    op.create_index(op.f('ix_bureaux_vote_numero_bureau'), 'bureaux_vote', ['numero_bureau'], unique=False)
    op.create_index(op.f('ix_bureaux_vote_numero_bureau_central'), 'bureaux_vote', ['numero_bureau_central'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bureaux_vote_numero_bureau_central'), table_name='bureaux_vote')
    op.drop_index(op.f('ix_bureaux_vote_numero_bureau'), table_name='bureaux_vote')
    op.drop_index(op.f('ix_bureaux_vote_commune'), table_name='bureaux_vote')
    op.drop_table('bureaux_vote')
    op.drop_index(op.f('ix_bureaux_centraux_numero_bureau_central'), table_name='bureaux_centraux')
    op.drop_index(op.f('ix_bureaux_centraux_commune'), table_name='bureaux_centraux')
    op.drop_table('bureaux_centraux')
    # ### end Alembic commands ###
